steps:
  - id: 'build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t',
           'gcr.io/$PROJECT_ID/github.com/kajekk/test-repo:$SHORT_SHA',
           '.']

  - id: 'push image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'gcr.io/$PROJECT_ID/github.com/kajekk/test-repo:$SHORT_SHA']

  - id: 'configure kubectl'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials "$${CLOUDSDK_CONTAINER_CLUSTER}" --zone "$${CLOUDSDK_COMPUTE_ZONE}"

  - id: 'deploy to k8s'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        kubectl set image deployment/test-repo test-repo-1=gcr.io/$PROJECT_ID/github.com/kajekk/test-repo:$SHORT_SHA